version: 1
builder:
   configs:
   - documentation_targets: ["CareKit", "CareKitUI", "CareKitStore", "CareKitFHIR"]
     platform: ios
     scheme: "CareKit"
   - platform: watchos
     scheme: "CareKit"
   - platform: macos
     scheme: "CareKit"
