language: swift 
osx_image: xcode12
xcode_workspace: CKWorkspace.xcworkspace
jobs:
  include:
    - xcode_scheme: CareKit iOS
      xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro Max
    - xcode_scheme: CareKitFHIR
      xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro Max
    - xcode_scheme: CareKitStore iOS
      xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro Max
    - xcode_scheme: CareKitUI iOS
      xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro Max
    - xcode_scheme: OCKCatalog
      xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro Max
    - xcode_scheme: OCKSample
      xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro Max

