# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/HippocratesTech/OTFCocoapodSpecs'

target 'OTFCareKit iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CareKitStore', '1.0'
  pod 'CareKitUI', '1.0'
  # pod 'CareKitUI', :path => '../'
  # pod 'CareKitStore', :path => '../'
  # Pods for CareKit iOS

end

target 'OTFCareKit Watch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CareKit Watch

end
